server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    username: postgres
    password: ilyas
    url: jdbc:postgresql://localhost:8081/customer
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true