server:
  port: 8083
spring:
  application:
    name: notification
  datasource:
    username: postgres
    password: ilyas
    url: jdbc:postgresql://localhost:8081/notification
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka